replicaCount: 1

image:
  repository: docker.io/abdosblz/biblio-gen
  pullPolicy: IfNotPresent
  tag: "0.0.0-2"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: www.gamevibes.fr
      paths:
        - path: /biblio
          pathType: Prefix

env:
  API_URL: "https://api.gamevibes.fr/api/v1"
